services:
  - type: web
    name: fototec
    env: node
    region: oregon
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3000
      - key: SMTP_USER
        value: fototecventass@gmail.com
      - key: RESEND_API_KEY
        sync: false
        # IMPORTANTE: Agregar en Render Dashboard > Environment > Environment Variables
        # RESEND_API_KEY = "re_xxxxxxxxxxxx"