services:
  - type: web
    name: fototec
    env: node
    region: oregon
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3000
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        value: fototecventass@gmail.com
      - key: SMTP_PASS
        sync: false
        # IMPORTANTE: Configurar como Variable de Entorno en el Dashboard de Render
        # Ir a: Render Dashboard > fototec > Environment > Environment Variables
        # Agregar: SMTP_PASS = "drhw ebwc ruoi rhbs"