services:
  - type: web
    name: fototec-web
    runtime: static
    region: oregon
    branch: main
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: PUBLIC_API_URL
        value: https://fototec-api.onrender.com/graphql
